FROM ghcr.io/void-linux/void-glibc-full:latest
MAINTAINER Floatstinger
RUN xbps-install -Sy firefox dejavu-fonts-ttf git
RUN git clone https://github.com/Floatstinger/.dotfiles.git
RUN mkdir -p /etc/firefox/policies
RUN cp .dotfiles/firefox/policies.json /etc/firefox/policies/
CMD ["/usr/bin/firefox"]