#!/bin/zsh

# container run command

podman run \
       --rm \
       --mount type=bind,source="${XDG_RUNTIME_DIR}/pipewire-0",target="/tmp/pipewire-0" --device /dev/snd \
       -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
       -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
       -v ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie \
       --mount type=bind,source="${HOME}/Downloads",target="/root/Downloads" \
       -e DISPLAY=$DISPLAY \
       -v ${HOME}/.Xauthority:/root/.Xauthority:ro \
       --device /dev/dri \
       --net=host \
       firefox:1.0 \
